"""Added fruit and youtube tables

Revision ID: bfdeab0e9ca8
Revises: 
Create Date: 2022-12-16 15:59:54.465654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdeab0e9ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob',
    sa.Column('blob_hash', sa.String(), nullable=True),
    sa.Column('blob_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('blob_path')
    )
    op.create_table('fruit',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('blob_type', sa.String(), nullable=True),
    sa.Column('fruit_name', sa.String(), nullable=True),
    sa.Column('fruit_color', sa.String(), nullable=True),
    sa.Column('blob_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('youtube',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('blob_type', sa.String(), nullable=True),
    sa.Column('blob_hash', sa.String(), nullable=True),
    sa.Column('photo_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube')
    op.drop_table('fruit')
    op.drop_table('blob')
    # ### end Alembic commands ###
